# docker file for local-development
#
FROM postgres:14

# packages and extensions
#
RUN apt-get update \
    && apt-get install -y \
        postgresql-14-pgtap \
        postgresql-14-cron \
        postgresql-14-partman \
        postgresql-14-postgis-3 \
        postgresql-plpython3-14 \
        libpq-dev \
        python3-pip \
        gdal-bin \
        git \
        jq

# build python modules
#
COPY requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

# some files
#
COPY ./create-multiple-postgresql-databases.sh /docker-entrypoint-initdb.d/
COPY test.sql /test.sql

# work directory
#
WORKDIR /work
